#!/bin/sh
set -eu

: "${POSTGRES_APP_PASSWORD:?set POSTGRES_APP_PASSWORD}"
: "${POSTGRES_WEBHOOK_PASSWORD:?set POSTGRES_WEBHOOK_PASSWORD}"

psql \
  --set=ON_ERROR_STOP=1 \
  --set=app_password="$POSTGRES_APP_PASSWORD" \
  --set=webhook_password="$POSTGRES_WEBHOOK_PASSWORD" \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<'SQL'
CREATE ROLE hk_platform
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS
  PASSWORD :'app_password';
CREATE ROLE hk_webhook_worker
  LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT BYPASSRLS
  PASSWORD :'webhook_password';
SQL
